# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14iLdcGPyH_jCDV2yIHfVEAWu1R6CMDQy
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
import math

df = pd.read_csv("Weather-related disease prediction.csv")
df

df.isnull().sum()
from sklearn.impute import SimpleImputer

imp = SimpleImputer(strategy='median')
df[['Temperature (C)','Humidity']] = imp.fit_transform(df[['Temperature (C)','Humidity']])

X = df.drop('prognosis', axis=1)
y = df['prognosis']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)
print("Accuracy:", model.score(X_test, y_test))

X = df[['Age']]
y = df['Temperature (C)']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

print("Coefficient (slope):", model.coef_)
print("Intercept:", model.intercept_)

y_pred = model.predict(X_test)

for i in range(10):
    print(f"Age: {X_test.iloc[i].values[0]}, Actual Temp: {y_test.iloc[i]}, Predicted Temp: {y_pred[i]:.2f}")

from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R2 Score:", r2)

df = df[['Age', 'Temperature (C)']].dropna()

from sklearn.model_selection import train_test_split

X = df[['Age']]
y = df['Temperature (C)']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

print("Coefficient:", model.coef_[0])
print("Intercept:", model.intercept_)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score

print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 score:", r2_score(y_test, y_pred))

import matplotlib.pyplot as plt

plt.scatter(X, y, color='blue', label='Actual')
plt.plot(X_test, y_pred, color='red', linewidth=2, label='Prediction')
plt.xlabel('Age')
plt.ylabel('Temperature (C)')
plt.legend()
plt.show()