# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fQk7ubFrb-tBxdDcPJJCRvLL6a-X4ri2
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
import math

df = pd.read_csv("hiring.csv")
df

word_to_num = {
    'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5,
    'six': 6, 'seven': 7, 'eight': 8, 'nine': 9, 'ten': 10, 'eleven': 11
}
df.experience = df.experience.fillna('one').apply(lambda x: word_to_num[x])
df

w = df['test_score(out of 10)'].median()
w

df = df.fillna(w)
df

model = linear_model.LinearRegression()
model.fit(df.drop('salary($)',axis=1),df['salary($)'])

model.predict([[2,9,6]])

model.predict([[12,10,10]])